version: '3.9'

services:
  api:
    build: .
    container_name: optionchain-api
    restart: always
    environment:
      DB_DSN: "postgres://optionuser:optionpass@<your_local_db_host>:5432/optionchain?sslmode=disable"
      PORT: "4300"
    ports:
      - "4300:4300"