version: '3.9'

services:
  fetcher:
    build:
      context: .
      dockerfile: internal/fetcher/fetcher.Dockerfile
    container_name: optionchain-fetcher
    restart: always
    environment:
      REDIS_URL: "${REDIS_URL}"

  processor:
    build:
      context: .
      dockerfile: internal/processing/processing.Dockerfile
    container_name: optionchain-processor
    restart: always
    environment:
      REDIS_URL: "${REDIS_URL}"
      DATABASE_URL: "${DATABASE_URL}"
      PORT: "${PORT:-8090}"
    ports:
      - "${PORT:-8090}:${PORT:-8090}"
